package com.pays;

import com.pays.ac.AcPayApi;
import com.pays.ali.Ali2BankPayApi;
import com.pays.ali.AliPayApi;
import com.pays.cn41.Cn41PayApi;
import com.pays.cnw.CnwAliPayApi;
import com.pays.cnw.CnwPayApi;
import com.pays.cnw.CnwWxPayApi;
import com.pays.cq.CqAliPayApi;
import com.pays.cq.CqWxPayApi;
import com.pays.daddy.DaddyAliPayApi;
import com.pays.daddy.DaddyNocardPayApi;
import com.pays.daddy.DaddyPayApi;
import com.pays.daddy.DaddyWxPayApi;
import com.pays.ddbill.DdbillAliPayApi;
import com.pays.ddbill.DdbillPayApi;
import com.pays.ddbill.DdbillWxPayApi;
import com.pays.din.DinPayApi;
import com.pays.din.DinRsaAliScanPayApi;
import com.pays.din.DinRsaPayApi;
import com.pays.din.DinRsaWxPayApi;
import com.pays.din.DinRsaWxScanPayApi;
import com.pays.din.DinRsaZhbScanPayApi;
import com.pays.e95.E95FastPayApi;
import com.pays.e95.E95PayApi;
import com.pays.ecpss.EcpssB2BPayApi;
import com.pays.ecpss.EcpssB2CCreditPayApi;
import com.pays.ecpss.EcpssB2CDebitPayApi;
import com.pays.ecpss.EcpssPayApi;
import com.pays.ecpss.EcpssnoCardPayApi;
import com.pays.ecpss.EcpssquickPayPayApi;
import com.pays.ejf.EjfAliPayApi;
import com.pays.ejf.EjfQQH5PayApi;
import com.pays.ejf.EjfQQScanPayApi;
import com.pays.ejf.EjfWxPayApi;
import com.pays.eka.EkaAliPayApi;
import com.pays.eka.EkaPayApi;
import com.pays.eka.EkaTenPayApi;
import com.pays.fun.FunPayApi;
import com.pays.fun.FunWxPayApi;
import com.pays.gloden.GlodenPayApi;
import com.pays.gloden.GlodenQQPayApi;
import com.pays.gloden.GlodenScanPayApi;
import com.pays.go.GoPayApi;
import com.pays.ips.IpsPayApi;
import com.pays.jf.JfAliPayApi;
import com.pays.jf.JfQQPayApi;
import com.pays.jf.JfWxPayApi;
import com.pays.jmoney.JmoneyPayApi;
import com.pays.jubao.JubaoPayApi;
import com.pays.juxin.JuxinAliScanPayApi;
import com.pays.juxin.JuxinAliWapPayApi;
import com.pays.juxin.JuxinPayApi;
import com.pays.juxin.JuxinQQScanPayApi;
import com.pays.juxin.JuxinQQWapPayApi;
import com.pays.juxin.JuxinWxPayApi;
import com.pays.juxin.JuxinWxWapPayApi;
import com.pays.keke.KeKePayApi;
import com.pays.keke.KeKeQuickPayApi;
import com.pays.kkl.KklPayApi;
import com.pays.le.LeAliPayApi;
import com.pays.le.LePayApi;
import com.pays.le.LeWxPayApi;
import com.pays.mm.MMAliPayApi;
import com.pays.mm.MMPayApi;
import com.pays.mm.MMQQPayApi;
import com.pays.mm.MMWxPayApi;
import com.pays.mobao.MobaoPayApi;
import com.pays.mobao.MobaoWxPayApi;
import com.pays.mobao.MobaoYlPayApi;
import com.pays.mobao.MobaoZfbPayApi;
import com.pays.myjop.MyjopPayApi;
import com.pays.myjop.MyjopScanAliPayApi;
import com.pays.myjop.MyjopScanQQPayApi;
import com.pays.myjop.MyjopScanWxPayApi;
import com.pays.myjop.MyjopScanYlPayApi;
import com.pays.nxiaoka.NxiaokaAliPayApi;
import com.pays.nxiaoka.NxiaokaAliScanPayApi;
import com.pays.nxiaoka.NxiaokaPayApi;
import com.pays.nxiaoka.NxiaokaQQPayApi;
import com.pays.nxiaoka.NxiaokaTenPayApi;
import com.pays.nxiaoka.NxiaokaWxPayApi;
import com.pays.qtong.QtongAliPayApi;
import com.pays.qtong.QtongPayApi;
import com.pays.qtong.QtongWxPayApi;
import com.pays.rfu.RfuAliPayApi;
import com.pays.rfu.RfuMobilePayApi;
import com.pays.rfu.RfuPayApi;
import com.pays.rfu.RfuWapPayApi;
import com.pays.rfu.RfuWxPayApi;
import com.pays.rfu.RfuYlPayApi;
import com.pays.swiftpass.SwiftpassPayApi;
import com.pays.ttflash.TtflashAliPayApi;
import com.pays.ttflash.TtflashPayApi;
import com.pays.ttflash.TtflashWxPayApi;
import com.pays.ttflash.TtflashYlPayApi;
import com.pays.un.UnAliH5PayApi;
import com.pays.un.UnAliScanPayApi;
import com.pays.un.UnPayApi;
import com.pays.un.UnQQScanPayApi;
import com.pays.un.UnWapPayApi;
import com.pays.un.UnWxH5PayApi;
import com.pays.un.UnWxScanPayApi;
import com.pays.un.UnYlScanPayApi;
import com.pays.w5.W5AliScanPayApi;
import com.pays.w5.W5PayApi;
import com.pays.w5.W5RsaAliScanPayApi;
import com.pays.w5.W5RsaQQScanPayApi;
import com.pays.w5.W5RsaWxScanPayApi;
import com.pays.w5.W5WxScanPayApi;
import com.pays.welink.WelinkAliPayApi;
import com.pays.welink.WelinkPayApi;
import com.pays.welink.WelinkWxPayApi;
import com.pays.welink.WelinkYlPayApi;
import com.pays.worth.WorthAliPayApi;
import com.pays.worth.WorthPayApi;
import com.pays.worth.WorthWxPayApi;
import com.pays.worth.WorthWxWapPayApi;
import com.pays.wx.WxPayApi;
import com.pays.xingxin.XingxinAliPayApi;
import com.pays.xingxin.XingxinPayApi;
import com.pays.xingxin.XingxinQQPayApi;
import com.pays.xingxin.XingxinWxPayApi;
import com.pays.xingxin.XingxinYlPayApi;
import com.pays.xingxin2.Xingxin2AliPayApi;
import com.pays.xingxin2.Xingxin2QQPayApi;
import com.pays.xingxin2.Xingxin2WxPayApi;
import com.pays.yee.YeeAliPayApi;
import com.pays.yee.YeePayApi;
import com.pays.yee.YeeTenPayApi;
import com.pays.yee.YeeWxPayApi;
import com.pays.yee.YeeWxWAPPayApi;
import com.pays.yee.YeeYlPayApi;
import com.pays.yeeyk.YeeykAliPayApi;
import com.pays.yeeyk.YeeykPayApi;
import com.pays.yeeyk.YeeykWxPayApi;
import com.pays.yjfl.YjflAliPayApi;
import com.pays.yjfl.YjflWxPayApi;
import com.pays.yom.YomAliPayApi;
import com.pays.yom.YomPayApi;
import com.pays.yom.YomWxPayApi;
import com.pays.yom.YomYlPayApi;
import com.pays.zb.ZbAliPayApi;
import com.pays.zb.ZbPayApi;
import com.pays.zb.ZbQQPayApi;
import com.pays.zb.ZbWeiXinPayApi;
import com.pays.zhih.ZhihAliPayApi;
import com.pays.zhih.ZhihPayApi;
import com.pays.zhih.ZhihWxPayApi;
import com.pays.zito.ZitoAliPayApi;
import com.pays.zito.ZitoPayApi;
import com.pays.zito.ZitoWxPayApi;
import com.pays.zsage.ZsageAliPayApi;
import com.pays.zsage.ZsagePayApi;
import com.pays.zsage.ZsageQQPayApi;
import com.pays.zsage.ZsageWxPayApi;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

public class PayApiFactory {
    private static Map<String, PayApi> maps = new HashMap<>();

    static {
//        maps.put("ac", new AcPayApi());
        maps.put("jmoney", new JmoneyPayApi());
        maps.put("kkl", new KklPayApi());
        maps.put("cn41", new Cn41PayApi());
        maps.put("din", new DinPayApi());
        maps.put("dinRsa", new DinRsaPayApi());
        maps.put("dinRsaWx", new DinRsaWxPayApi());
        maps.put("dinRsaAliScan", new DinRsaAliScanPayApi());
        maps.put("dinRsaWxScan", new DinRsaWxScanPayApi());
        maps.put("dinRsaZhbScan", new DinRsaZhbScanPayApi());
        maps.put("zhih", new ZhihPayApi());
        maps.put("zhihWx", new ZhihWxPayApi());
        maps.put("zhihAli", new ZhihAliPayApi());
        maps.put("ips", new IpsPayApi());
        maps.put("go", new GoPayApi());
        maps.put("jubao", new JubaoPayApi());
        maps.put("mobao", new MobaoPayApi());
        maps.put("mobaoWx", new MobaoWxPayApi());
        maps.put("mobaoYl", new MobaoYlPayApi());
        maps.put("mobaoZfb", new MobaoZfbPayApi());
        maps.put("ecpss", new EcpssPayApi());
        maps.put("ecpssB2B", new EcpssB2BPayApi());
        maps.put("ecpssB2CCredit", new EcpssB2CCreditPayApi());
        maps.put("ecpssB2CDebit", new EcpssB2CDebitPayApi());
        maps.put("ecpssnoCard", new EcpssnoCardPayApi());
        maps.put("ecpssquickPay", new EcpssquickPayPayApi());
        maps.put("wxpay", new WxPayApi());
        maps.put("alipay", new AliPayApi());
        maps.put("fun", new FunPayApi());
        maps.put("funWx", new FunWxPayApi());
        maps.put("yee", new YeePayApi());
        maps.put("yeeYl", new YeeYlPayApi());
        maps.put("yeeWx", new YeeWxPayApi());
        maps.put("yeeAli", new YeeAliPayApi());
        maps.put("yeeWxWap", new YeeWxWAPPayApi());
        maps.put("yeeTen", new YeeTenPayApi());
        maps.put("yom", new YomPayApi());
        maps.put("yomWx", new YomWxPayApi());
        maps.put("yomAli", new YomAliPayApi());
        maps.put("yomWx", new YomYlPayApi());
        maps.put("rfu", new RfuPayApi());
        maps.put("rfuWx", new RfuWxPayApi());
        maps.put("rfuAli", new RfuAliPayApi());
        maps.put("rfuYl", new RfuYlPayApi());
        maps.put("rfuWap", new RfuWapPayApi());
        maps.put("rfuMobile", new RfuMobilePayApi());
        maps.put("nxiaoka", new NxiaokaPayApi());
        maps.put("nxiaokaAli", new NxiaokaAliPayApi());
        maps.put("nxiaokaAliScan", new NxiaokaAliScanPayApi());
        maps.put("nxiaokaQQ", new NxiaokaQQPayApi());
        maps.put("nxiaokaTen", new NxiaokaTenPayApi());
        maps.put("nxiaokaWx", new NxiaokaWxPayApi());
        maps.put("worth", new WorthPayApi());
        maps.put("worthWx", new WorthWxPayApi());
        maps.put("worthWxWap", new WorthWxWapPayApi());
        maps.put("worthAli", new WorthAliPayApi());
        maps.put("ttflashAli", new TtflashAliPayApi());
        maps.put("ttflash", new TtflashPayApi());
        maps.put("ttflashWx", new TtflashWxPayApi());
        maps.put("ttflashYl", new TtflashYlPayApi());
        maps.put("ekaAli", new EkaAliPayApi());
        maps.put("eka", new EkaPayApi());
        maps.put("ekaTen", new EkaTenPayApi());
        maps.put("cnw", new CnwPayApi());
        maps.put("cnwWx", new CnwWxPayApi());
        maps.put("cnwAli", new CnwAliPayApi());
        maps.put("cqAli", new CqAliPayApi());
        maps.put("cqWx", new CqWxPayApi());
        maps.put("ejfWx", new EjfWxPayApi());
        maps.put("ejfAli", new EjfAliPayApi());
        maps.put("ejfQQScan", new EjfQQScanPayApi());
        maps.put("ejfQQH5", new EjfQQH5PayApi());
        maps.put("daddy", new DaddyPayApi());
        maps.put("daddyWx", new DaddyWxPayApi());
        maps.put("daddyAli", new DaddyAliPayApi());
        maps.put("daddyNocard", new DaddyNocardPayApi());
        maps.put("e95", new E95PayApi());
        maps.put("e95fast", new E95FastPayApi());
        maps.put("yeeyk", new YeeykPayApi());
        maps.put("yeeykWx", new YeeykWxPayApi());
        maps.put("yeeykAli", new YeeykAliPayApi());
        maps.put("jfWx", new JfWxPayApi());
        maps.put("jfAli", new JfAliPayApi());
        maps.put("jfQq", new JfQQPayApi());
        maps.put("zsage", new ZsagePayApi());
        maps.put("zsageWx", new ZsageWxPayApi());
        maps.put("zsageAli", new ZsageAliPayApi());
        maps.put("zsageQQ", new ZsageQQPayApi());
        maps.put("ddbill", new DdbillPayApi());
        maps.put("ddbillWx", new DdbillWxPayApi());
        maps.put("ddbillAli", new DdbillAliPayApi());
        maps.put("swiftpass", new SwiftpassPayApi());
        maps.put("qtong", new QtongPayApi());
        maps.put("welink", new WelinkPayApi());
        maps.put("welinkWx", new WelinkWxPayApi());
        maps.put("welinkAli", new WelinkAliPayApi());
        maps.put("welinkYl", new WelinkYlPayApi());
        maps.put("w5", new W5PayApi());
        maps.put("w5WxScan", new W5WxScanPayApi());
        maps.put("w5AliScan", new W5AliScanPayApi());
        maps.put("zito", new ZitoPayApi());
        maps.put("zitoWx", new ZitoWxPayApi());
        maps.put("zitoAli", new ZitoAliPayApi());
        maps.put("alipay2bank", new Ali2BankPayApi());
        maps.put("gloden", new GlodenPayApi());
        maps.put("glodenScan", new GlodenScanPayApi());
        maps.put("glodenQQ", new GlodenQQPayApi());
        maps.put("juxinAliScan", new JuxinAliScanPayApi());
        maps.put("juxinAliWap", new JuxinAliWapPayApi());
        maps.put("juxin", new JuxinPayApi());
        maps.put("juxinQQScan", new JuxinQQScanPayApi());
        maps.put("juxinQQWap", new JuxinQQWapPayApi());
        maps.put("juxinWx", new JuxinWxPayApi());
        maps.put("juxinWxWap", new JuxinWxWapPayApi());
        maps.put("yjflWx", new YjflWxPayApi());
        maps.put("yjflAli", new YjflAliPayApi());
        maps.put("xingxinAli", new XingxinAliPayApi());
        maps.put("xingxin", new XingxinPayApi());
        maps.put("xingxinQQ", new XingxinQQPayApi());
        maps.put("xingxinWx", new XingxinWxPayApi());
        maps.put("xingxinYl", new XingxinYlPayApi());
        maps.put("leAli", new LeAliPayApi());
        maps.put("le", new LePayApi());
        maps.put("leWx", new LeWxPayApi());
        maps.put("w5RsaAliScan", new W5RsaAliScanPayApi());
        maps.put("w5RsaWxScan", new W5RsaWxScanPayApi());
        maps.put("w5RsaQQScan", new W5RsaQQScanPayApi());
        maps.put("qtong", new QtongPayApi());
        maps.put("qtongWx", new QtongWxPayApi());
        maps.put("qtongAli", new QtongAliPayApi());
        maps.put("zb", new ZbPayApi());
        maps.put("zbAli", new ZbAliPayApi());
        maps.put("zbWx", new ZbWeiXinPayApi());
        maps.put("zbQQ", new ZbQQPayApi());
        maps.put("mm", new MMPayApi());
        maps.put("mmAli", new MMAliPayApi());
        maps.put("mmWx", new MMWxPayApi());
        maps.put("mmQQ", new MMQQPayApi());
        maps.put("keke", new KeKePayApi());
        maps.put("kekeQuick", new KeKeQuickPayApi());
        maps.put("unAliH5", new UnAliH5PayApi());
        maps.put("unAliScan", new UnAliScanPayApi());
        maps.put("un", new UnPayApi());
        maps.put("unQQScan", new UnQQScanPayApi());
        maps.put("unWap", new UnWapPayApi());
        maps.put("unWxH5", new UnWxH5PayApi());
        maps.put("unWxScan", new UnWxScanPayApi());
        maps.put("unYlScan", new UnYlScanPayApi());
        maps.put("xingxin2Ali", new Xingxin2AliPayApi());
        maps.put("xingxin2QQ", new Xingxin2QQPayApi());
        maps.put("xingxin2Wx", new Xingxin2WxPayApi());
        maps.put("myjop", new MyjopPayApi());
        maps.put("myjopScanWx", new MyjopScanWxPayApi());
        maps.put("myjopScanAli", new MyjopScanAliPayApi());
        maps.put("myjopScanYl", new MyjopScanYlPayApi());
        maps.put("myjopScanQQ", new MyjopScanQQPayApi());
    }

    public static Map<String, String> getMaps() {
        Map<String, String> titles = new TreeMap();
        List<String> keys = new ArrayList(maps.keySet());
        Collections.sort(keys);
        for (String k : keys) {
            titles.put(k, ((PayApi) maps.get(k)).getTitle());
        }
        return titles;
    }

    public static PayApi getInstance(String key) {
        if (maps.containsKey(key)) {
            return (PayApi) maps.get(key);
        }
        return null;
    }

    public static boolean isTwoCode(String classKey) {
        return ("wxpay".equals(classKey)) || ("alipay".equals(classKey)) || ("alipay2bank".equals(classKey));
    }
}
